[package]
name = "littlemanplus"
version = "0.1.0"
edition = "2024"
license = "GPL-3"

[dependencies]
lmp-lang = {path = "../lmp-lang"}
lmp-common = {path = "../lmp-common"}
thiserror = "2.0.12"
ratatui = "0.29.0"
tui-textarea = "0.7.0"
