[package]
name = "lmp-lang"
version = "0.1.0"
edition = "2024"
license = "GPL-3"

[dependencies]
chumsky = { version = "0.10.1", features = ["regex"]}
lmp-common = { path = "../lmp-common" }

[dev-dependencies]
indoc = "2.0.6"